=== CDOT-CV/jpo-geojsonconverter/jpo-geojsonconverter/src/main/resources/schemas/processed-tim.schema.json
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "$defs" : {
    "Ieee1609Dot2SignedDataMetadata" : {
      "type" : "object",
      "properties" : {
        "certificateValidityEnd" : {
          "type" : "string",
          "format" : "date-time"
        },
        "certificateValidityStart" : {
          "type" : "string",
          "format" : "date-time"
        },
        "generationTime" : {
          "type" : "string",
          "format" : "date-time"
        },
        "psid" : {
          "type" : "integer",
          "format" : "int32"
        }
      }
    },
    "Point-1" : {
      "type" : "object",
      "properties" : {
        "bbox" : {
          "type" : "array",
          "items" : {
            "type" : "number",
            "format" : "double"
          }
        },
        "coordinates" : {
          "type" : "array",
          "items" : {
            "type" : "number",
            "format" : "double"
          }
        }
      }
    },
    "Point-2" : {
      "$ref" : "#/$defs/Point-1",
      "type" : "object",
      "properties" : {
        "type" : {
          "const" : "Point"
        }
      },
      "required" : [ "type" ]
    },
    "ProcessedAnchorPoint" : {
      "type" : "object",
      "properties" : {
        "elevationMeters" : {
          "type" : "number",
          "format" : "double"
        },
        "latitude" : {
          "type" : "number",
          "format" : "double"
        },
        "longitude" : {
          "type" : "number",
          "format" : "double"
        }
      }
    },
    "ProcessedCircleRegionInfo-1" : {
      "type" : "object",
      "properties" : {
        "anchorPoint" : {
          "$ref" : "#/$defs/ProcessedAnchorPoint"
        },
        "directionInfo" : {
          "anyOf" : [ {
            "$ref" : "#/$defs/ProcessedDirectionalityDirectionInfo-2"
          }, {
            "$ref" : "#/$defs/ProcessedHeadingDirectionInfo-2"
          } ]
        },
        "elevationProfile" : {
          "$ref" : "#/$defs/ProcessedElevationProfile"
        },
        "geometryIndex" : {
          "type" : "integer",
          "format" : "int32"
        },
        "radius" : {
          "type" : "number",
          "format" : "double"
        },
        "regionType" : {
          "$ref" : "#/$defs/ProcessedRegionType"
        }
      }
    },
    "ProcessedCircleRegionInfo-2" : {
      "$ref" : "#/$defs/ProcessedCircleRegionInfo-1",
      "type" : "object",
      "properties" : {
        "regionType" : {
          "const" : "CIRCLE"
        }
      },
      "required" : [ "regionType" ]
    },
    "ProcessedContentType" : {
      "type" : "string",
      "enum" : [ "ADVISORY", "WORK_ZONE", "SPEED_LIMIT", "GENERIC_SIGN", "EXIT_SERVICE" ]
    },
    "ProcessedDeploymentAgency" : {
      "type" : "string",
      "enum" : [ "STATE_OR_LOCAL", "COMMERCIAL", "UNKNOWN" ]
    },
    "ProcessedDirectionType" : {
      "type" : "string",
      "enum" : [ "DIRECTIONALITY", "HEADING" ]
    },
    "ProcessedDirectionality" : {
      "type" : "string",
      "enum" : [ "forward", "reverse", "both", "unavailable", "unknown" ]
    },
    "ProcessedDirectionalityDirectionInfo-1" : {
      "type" : "object",
      "properties" : {
        "directionType" : {
          "$ref" : "#/$defs/ProcessedDirectionType"
        },
        "directionality" : {
          "$ref" : "#/$defs/ProcessedDirectionality"
        }
      }
    },
    "ProcessedDirectionalityDirectionInfo-2" : {
      "$ref" : "#/$defs/ProcessedDirectionalityDirectionInfo-1",
      "type" : "object",
      "properties" : {
        "directionType" : {
          "const" : "DIRECTIONALITY"
        }
      },
      "required" : [ "directionType" ]
    },
    "ProcessedElevationProfile" : {
      "type" : "object",
      "properties" : {
        "defaultElevationMeters" : {
          "type" : "number",
          "format" : "double"
        },
        "nodeElevationMeters" : {
          "type" : "array",
          "items" : {
            "type" : [ "number", "null" ],
            "format" : "double"
          }
        }
      }
    },
    "ProcessedHeading" : {
      "type" : "object",
      "properties" : {
        "heading" : {
          "type" : "number",
          "format" : "double"
        },
        "range" : {
          "type" : "number",
          "format" : "double"
        }
      }
    },
    "ProcessedHeadingDirectionInfo-1" : {
      "type" : "object",
      "properties" : {
        "directionType" : {
          "$ref" : "#/$defs/ProcessedDirectionType"
        },
        "headingList" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/$defs/ProcessedHeading"
          }
        }
      }
    },
    "ProcessedHeadingDirectionInfo-2" : {
      "$ref" : "#/$defs/ProcessedHeadingDirectionInfo-1",
      "type" : "object",
      "properties" : {
        "directionType" : {
          "const" : "HEADING"
        }
      },
      "required" : [ "directionType" ]
    },
    "ProcessedLaneWidthProfile" : {
      "type" : "object",
      "properties" : {
        "defaultWidthMeters" : {
          "type" : "number",
          "format" : "double"
        },
        "nodeLaneWidthMeters" : {
          "type" : "array",
          "items" : {
            "type" : [ "number", "null" ],
            "format" : "double"
          }
        }
      }
    },
    "ProcessedPathRegionInfo-1" : {
      "type" : "object",
      "properties" : {
        "anchorPoint" : {
          "$ref" : "#/$defs/ProcessedAnchorPoint"
        },
        "directionInfo" : {
          "anyOf" : [ {
            "$ref" : "#/$defs/ProcessedDirectionalityDirectionInfo-2"
          }, {
            "$ref" : "#/$defs/ProcessedHeadingDirectionInfo-2"
          } ]
        },
        "elevationProfile" : {
          "$ref" : "#/$defs/ProcessedElevationProfile"
        },
        "geometryIndex" : {
          "type" : "integer",
          "format" : "int32"
        },
        "laneWidthProfile" : {
          "$ref" : "#/$defs/ProcessedLaneWidthProfile"
        },
        "regionType" : {
          "$ref" : "#/$defs/ProcessedRegionType"
        }
      }
    },
    "ProcessedPathRegionInfo-2" : {
      "$ref" : "#/$defs/ProcessedPathRegionInfo-1",
      "type" : "object",
      "properties" : {
        "regionType" : {
          "const" : "PATH"
        }
      },
      "required" : [ "regionType" ]
    },
    "ProcessedPolygonRegionInfo-1" : {
      "type" : "object",
      "properties" : {
        "anchorPoint" : {
          "$ref" : "#/$defs/ProcessedAnchorPoint"
        },
        "directionInfo" : {
          "anyOf" : [ {
            "$ref" : "#/$defs/ProcessedDirectionalityDirectionInfo-2"
          }, {
            "$ref" : "#/$defs/ProcessedHeadingDirectionInfo-2"
          } ]
        },
        "elevationProfile" : {
          "$ref" : "#/$defs/ProcessedElevationProfile"
        },
        "geometryIndex" : {
          "type" : "integer",
          "format" : "int32"
        },
        "regionType" : {
          "$ref" : "#/$defs/ProcessedRegionType"
        }
      }
    },
    "ProcessedPolygonRegionInfo-2" : {
      "$ref" : "#/$defs/ProcessedPolygonRegionInfo-1",
      "type" : "object",
      "properties" : {
        "regionType" : {
          "const" : "POLYGON"
        }
      },
      "required" : [ "regionType" ]
    },
    "ProcessedRegionType" : {
      "type" : "string",
      "enum" : [ "PATH", "POLYGON", "CIRCLE", "UNKNOWN" ]
    },
    "ProcessedTimContent" : {
      "type" : "object",
      "properties" : {
        "contentItems" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/$defs/ProcessedTimContentItem"
          }
        },
        "sentence" : {
          "type" : "string"
        },
        "type" : {
          "$ref" : "#/$defs/ProcessedContentType"
        }
      }
    },
    "ProcessedTimContentItem" : {
      "type" : "object",
      "properties" : {
        "itisCode" : {
          "type" : "integer",
          "format" : "int64"
        },
        "itisPhrase" : {
          "type" : "string"
        },
        "type" : {
          "$ref" : "#/$defs/TimContentItemType"
        }
      }
    },
    "ProcessedTimFeature(Object)" : {
      "type" : "object",
      "properties" : {
        "geometry" : { },
        "id" : {
          "type" : "integer",
          "format" : "int32"
        },
        "properties" : {
          "$ref" : "#/$defs/ProcessedTimProperties"
        }
      }
    },
    "ProcessedTimFeatureCollection" : {
      "type" : "object",
      "properties" : {
        "features" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/$defs/ProcessedTimFeature(Object)"
          }
        }
      }
    },
    "ProcessedTimProperties" : {
      "type" : "object",
      "properties" : {
        "content" : {
          "$ref" : "#/$defs/ProcessedTimContent"
        },
        "deploymentAgencyType" : {
          "$ref" : "#/$defs/ProcessedDeploymentAgency"
        },
        "priority" : {
          "type" : "integer",
          "format" : "int32"
        },
        "regionInfoList" : {
          "type" : "array",
          "items" : {
            "anyOf" : [ {
              "$ref" : "#/$defs/ProcessedPathRegionInfo-2"
            }, {
              "$ref" : "#/$defs/ProcessedPolygonRegionInfo-2"
            }, {
              "$ref" : "#/$defs/ProcessedCircleRegionInfo-2"
            }, {
              "$ref" : "#/$defs/ProcessedUnknownRegionInfo-2"
            } ]
          }
        },
        "validityPeriod" : {
          "$ref" : "#/$defs/ProcessedValidityPeriod"
        }
      }
    },
    "ProcessedUnknownRegionInfo-1" : {
      "type" : "object",
      "properties" : {
        "anchorPoint" : {
          "$ref" : "#/$defs/ProcessedAnchorPoint"
        },
        "directionInfo" : {
          "anyOf" : [ {
            "$ref" : "#/$defs/ProcessedDirectionalityDirectionInfo-2"
          }, {
            "$ref" : "#/$defs/ProcessedHeadingDirectionInfo-2"
          } ]
        },
        "elevationProfile" : {
          "$ref" : "#/$defs/ProcessedElevationProfile"
        },
        "geometryIndex" : {
          "type" : "integer",
          "format" : "int32"
        },
        "laneWidthProfile" : {
          "$ref" : "#/$defs/ProcessedLaneWidthProfile"
        },
        "regionType" : {
          "$ref" : "#/$defs/ProcessedRegionType"
        }
      }
    },
    "ProcessedUnknownRegionInfo-2" : {
      "$ref" : "#/$defs/ProcessedUnknownRegionInfo-1",
      "type" : "object",
      "properties" : {
        "regionType" : {
          "const" : "UNKNOWN"
        }
      },
      "required" : [ "regionType" ]
    },
    "ProcessedValidationMessage" : {
      "type" : "object",
      "properties" : {
        "exception" : {
          "type" : "string"
        },
        "jsonPath" : {
          "type" : "string"
        },
        "message" : {
          "type" : "string"
        },
        "schemaPath" : {
          "type" : "string"
        }
      }
    },
    "ProcessedValidityPeriod" : {
      "type" : "object",
      "properties" : {
        "endTime" : {
          "type" : "string",
          "format" : "date-time"
        },
        "startTime" : {
          "type" : "string",
          "format" : "date-time"
        }
      }
    },
    "TimContentItemType" : {
      "type" : "string",
      "enum" : [ "ITIS_CODE", "PLAIN_TEXT" ]
    }
  },
  "type" : "object",
  "properties" : {
    "asn1" : {
      "type" : "string"
    },
    "dataFrameFeatureCollection" : {
      "$ref" : "#/$defs/ProcessedTimFeatureCollection"
    },
    "isCertPresent" : {
      "type" : "boolean"
    },
    "location" : {
      "$ref" : "#/$defs/Point-2"
    },
    "messageType" : {
      "type" : "string"
    },
    "msgCnt" : {
      "type" : "integer",
      "format" : "int32"
    },
    "odeReceivedAt" : {
      "type" : "string"
    },
    "originIp" : {
      "type" : "string"
    },
    "packetId" : {
      "type" : "string"
    },
    "schemaVersion" : {
      "type" : "integer",
      "format" : "int32"
    },
    "signedDataMetadata" : {
      "$ref" : "#/$defs/Ieee1609Dot2SignedDataMetadata"
    },
    "timeStamp" : {
      "type" : "string",
      "format" : "date-time"
    },
    "validationMessages" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/$defs/ProcessedValidationMessage"
      }
    }
  }
}

=== CDOT-CV/jpo-geojsonconverter/jpo-geojsonconverter/src/test/resources/json/sample.processed-tim-cert-present.json
{
    "schemaVersion": 1,
    "messageType": "TIM",
    "odeReceivedAt": "2025-10-07T21:40:19.711Z",
    "originIp": "172.27.0.1",
    "asn1": "001f81bc7015e5d818d4a500000d7ba1330f775d9b220200003f4b157e7d004011e94ed2a473397c14bb1e6005dc800c22df18a5bf6ffea0d1959039bfe5b85977ecc2d76ca4666715b1834646a0b95a86c78278538f4a76952399cbe0a5d8f3002ee4006116f8c50dfb7ff55cdff2dc04ce0b2efd985aed9484cce2b63572b50d823ce3c13c29c000146a3e1e200fad004306232221040400007e962afcfa008003529da5931e72f88b6a3cc00bb80081e506a76326ebec84432e6c22d467c21fdeb640ce1c9a211d70d90d8b27a20b1607c174641c000146a341e200fad004306232221040400007e962f70fa004003529da59af672f839e83ce805b843c03d4ed2cd7b397c1cf417263e94000041b040a808d4050100001fa58bdc3e801000dca76971269cbdfc3e8f3a016e81e00008b78daf64c53ba67f7f2c071aa5f17106a0690000043608140b40400007e962afcfa008023d29da548e672f829763cc00bb9001845be31437edffd4737fcb70b2efd985aed9484cce2b63172b50d8f04f0a71e94ed2a473397c14bb1e6005dc800c22df18a1bf6ffea39bfe5b85977ecc2d76ca4266715b18b95a86c7827853800028d47c3c401f5a00860c4644420",
    "msgCnt": 1,
    "timeStamp": "2025-09-26T10:00:00Z",
    "packetId": "18D4A500000D7BA133",
    "location": {
        "type": "Point",
        "coordinates": [
            -83.5565857,
            42.24326267
        ]
    },
    "validationMessages": [],
    "dataFrameFeatureCollection": {
        "features": [
            {
                "type": "Feature",
                "id": 0,
                "geometry": {
                    "type": "MultiLineString",
                    "coordinates": [
                        [
                            [
                                -83.55685122,
                                42.24260184
                            ],
                            [
                                -83.55685572,
                                42.24296949
                            ],
                            [
                                -83.55674691,
                                42.24318675
                            ],
                            [
                                -83.55659969,
                                42.24335721
                            ],
                            [
                                -83.55642973,
                                42.24346413
                            ],
                            [
                                -83.55583159,
                                42.24372648
                            ],
                            [
                                -83.5556344,
                                42.24377499
                            ],
                            [
                                -83.55538067,
                                42.24379002
                            ]
                        ],
                        [
                            [
                                -83.55685122,
                                42.24260184
                            ],
                            [
                                -83.55685572,
                                42.24296949
                            ],
                            [
                                -83.55674691,
                                42.24318675
                            ],
                            [
                                -83.55659969,
                                42.24335721
                            ],
                            [
                                -83.55642973,
                                42.24346413
                            ],
                            [
                                -83.55583159,
                                42.24372648
                            ],
                            [
                                -83.5556344,
                                42.24377499
                            ],
                            [
                                -83.55538067,
                                42.24379002
                            ]
                        ]
                    ]
                },
                "properties": {
                    "deploymentAgencyType": "STATE_OR_LOCAL",
                    "validityPeriod": {
                        "startTime": "2025-10-08T17:00:19.711Z",
                        "endTime": "9999-12-31T23:59:59.999Z",
                        "infinite": true
                    },
                    "priority": 2,
                    "regionInfoList": [
                        {
                            "regionType": "PATH",
                            "geometryIndex": 0,
                            "elevationProfile": {
                                "defaultElevationMeters": 368.0,
                                "nodeElevationMeters": [
                                    368.0,
                                    370.0,
                                    370.0,
                                    370.0,
                                    370.0,
                                    367.0,
                                    367.0,
                                    367.0
                                ]
                            },
                            "anchorPoint": {
                                "latitude": 42.2427507,
                                "longitude": -83.5566916,
                                "elevationMeters": 368.0
                            },
                            "directionInfo": {
                                "directionType": "DIRECTIONALITY",
                                "directionality": "forward"
                            },
                            "laneWidthProfile": {
                                "defaultWidthMeters": 7.5,
                                "nodeLaneWidthMeters": [
                                    7.5,
                                    8.0,
                                    8.0,
                                    8.0,
                                    8.0,
                                    8.5,
                                    8.5,
                                    8.5
                                ]
                            }
                        },
                        {
                            "regionType": "PATH",
                            "geometryIndex": 1,
                            "elevationProfile": {
                                "defaultElevationMeters": 368.0,
                                "nodeElevationMeters": [
                                    368.0,
                                    368.0,
                                    367.0,
                                    367.0,
                                    367.0,
                                    367.0,
                                    367.0,
                                    367.0
                                ]
                            },
                            "anchorPoint": {
                                "latitude": 42.2427507,
                                "longitude": -83.5566916,
                                "elevationMeters": 368.0
                            },
                            "directionInfo": {
                                "directionType": "DIRECTIONALITY",
                                "directionality": "forward"
                            },
                            "laneWidthProfile": {
                                "defaultWidthMeters": 7.5,
                                "nodeLaneWidthMeters": [
                                    7.5,
                                    7.5,
                                    7.5,
                                    7.5,
                                    7.5,
                                    7.5,
                                    7.25,
                                    7.25
                                ]
                            }
                        }
                    ],
                    "content": {
                        "type": "ADVISORY",
                        "contentItems": [
                            {
                                "type": "ITIS_CODE",
                                "itisCode": 13599,
                                "itisPhrase": "right-turn"
                            },
                            {
                                "type": "ITIS_CODE",
                                "itisCode": 7712,
                                "itisPhrase": "advice"
                            },
                            {
                                "type": "ITIS_CODE",
                                "itisCode": 8026,
                                "itisPhrase": "on-curve"
                            },
                            {
                                "type": "ITIS_CODE",
                                "itisCode": 268,
                                "itisPhrase": "speed-limit"
                            },
                            {
                                "type": "ITIS_CODE",
                                "itisCode": 12569,
                                "itisPhrase": "n25"
                            },
                            {
                                "type": "ITIS_CODE",
                                "itisCode": 8720,
                                "itisPhrase": "mPH"
                            }
                        ],
                        "sentence": "right-turn advice on-curve speed-limit n25 mPH"
                    }
                }
            },
            {
                "type": "Feature",
                "id": 1,
                "geometry": {
                    "type": "LineString",
                    "coordinates": [
                        [
                            -83.55514979,
                            42.24382121
                        ],
                        [
